Fix pending gem failure on armrest
It looks like not all the active support files are required for
armrest to be properly instantiated.

This can be fixed in our gem or in armrest.

activesupport/lib/active_support/core_ext/date_and_time/compatibility.rb:10:
in `<module:Compatibility>': undefined method `mattr_accessor'
for DateAndTime::Compatibility:Module (NoMethodError)